{% set version = "1.22.0" %}

package:
  name: csa
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/sakov/csa-c/archive/v{{ version }}.tar.gz
  sha256: b6d6ebeea146e09fc7aef827a3a3b22b7af674c2f0c67169c2275237e54c0c02

build:
  number: 2

requirements:
  build:
    - toolchain
    - posix  # [win]
    - m2w64-toolchain  # [win]

test:
  commands:
    - csabathy -V  # [not win]
    - csabathy.exe -V  # [win]
    - conda inspect linkages -p $PREFIX csa  # [not win]
    - conda inspect objects -p $PREFIX csa  # [osx]

about:
  home: https://github.com/sakov/csa-c
  license: BSD 2-Clause
  # license_file: LICENSE
  summary: 'Cubic Spline Approximation.'

extra:
  recipe-maintainers:
    - ocefpaf
